# Generated by Django 4.2.3 on 2023-08-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=50, verbose_name='период рассылки')),
            ],
            options={
                'verbose_name': 'период',
                'verbose_name_plural': 'период',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mailing', models.DateTimeField(auto_now_add=True, verbose_name='дата рассылки')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.frequency', verbose_name='период рассылки')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.status', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
