# Generated by Django 4.2.3 on 2023-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_emaillog_options_alter_emailmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='mailing.emailmessage', verbose_name='сообщение'),
        ),
    ]
