# Generated by Django 4.2.3 on 2023-08-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_emailsettings_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='message',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.emailmessage', verbose_name='сообщение'),
        ),
    ]
