# Generated by Django 4.2.3 on 2023-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
