# Generated by Django 4.2.3 on 2023-08-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_date_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_last_change',
            field=models.DateTimeField(verbose_name='дата последнего изменения'),
        ),
    ]
